# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(500, 248)
        Login.setMaximumSize(QtCore.QSize(500, 248))
        Login.setSizeIncrement(QtCore.QSize(500, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Login.setWindowIcon(icon)
        Login.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(Login)
        self.label.setGeometry(QtCore.QRect(20, 20, 461, 211))
        self.label.setStyleSheet("color: rgb(151, 0, 111);")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Login)
        self.label_2.setGeometry(QtCore.QRect(390, 10, 81, 21))
        self.label_2.setStyleSheet("color: rgb(151, 0, 111);\n"
"background-color: rgb(255, 255, 255);")
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.password = QtWidgets.QLineEdit(Login)
        self.password.setGeometry(QtCore.QRect(71, 120, 281, 22))
        self.password.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(151, 0, 111);\n"
"border-color: rgb(151, 0, 111);\n"
"padding : 2px;")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.newAccountBtn = QtWidgets.QPushButton(Login)
        self.newAccountBtn.setGeometry(QtCore.QRect(70, 160, 141, 24))
        self.newAccountBtn.setStyleSheet("background-color: rgb(151, 0, 111);\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Bernard MT Condensed\";\n"
"")
        self.newAccountBtn.setObjectName("newAccountBtn")
        self.user = QtWidgets.QLineEdit(Login)
        self.user.setGeometry(QtCore.QRect(70, 70, 281, 21))
        self.user.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(151, 0, 111);\n"
"border-color: rgb(151, 0, 111);\n"
"padding : 2px;")
        self.user.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.user.setObjectName("user")
        self.userL = QtWidgets.QLabel(Login)
        self.userL.setGeometry(QtCore.QRect(360, 70, 81, 21))
        self.userL.setStyleSheet("color: rgb(151, 0, 111);\n"
"background-color: rgb(255, 255, 255);")
        self.userL.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.userL.setAlignment(QtCore.Qt.AlignCenter)
        self.userL.setObjectName("userL")
        self.passwordL = QtWidgets.QLabel(Login)
        self.passwordL.setGeometry(QtCore.QRect(380, 120, 59, 16))
        self.passwordL.setStyleSheet("color: rgb(151, 0, 111);\n"
"background-color: rgb(255, 255, 255);")
        self.passwordL.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.passwordL.setAlignment(QtCore.Qt.AlignCenter)
        self.passwordL.setObjectName("passwordL")
        self.ok = QtWidgets.QPushButton(Login)
        self.ok.setGeometry(QtCore.QRect(220, 160, 131, 24))
        self.ok.setStyleSheet("background-color: rgb(151, 0, 111);\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Bernard MT Condensed\";\n"
"")
        self.ok.setObjectName("ok")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.label_2.setText(_translate("Login", "تسجيل الدخول"))
        self.password.setPlaceholderText(_translate("Login", "كلمة المرور"))
        self.newAccountBtn.setText(_translate("Login", "انشاء حساب"))
        self.user.setPlaceholderText(_translate("Login", "اسم المستخدم"))
        self.userL.setText(_translate("Login", "اسم المستخدم :"))
        self.passwordL.setText(_translate("Login", "كلمة المرور :"))
        self.ok.setText(_translate("Login", "تسجيل الدخول"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QDialog()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
