# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_newUser(object):
    def setupUi(self, newUser):
        newUser.setObjectName("newUser")
        newUser.resize(500, 291)
        newUser.setMinimumSize(QtCore.QSize(500, 291))
        newUser.setMaximumSize(QtCore.QSize(500, 16777215))
        newUser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.NameText = QtWidgets.QLineEdit(newUser)
        self.NameText.setGeometry(QtCore.QRect(71, 120, 291, 22))
        self.NameText.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(151, 0, 111);\n"
"border-color: rgb(151, 0, 111);\n"
"padding : 2px;")
        self.NameText.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.NameText.setObjectName("NameText")
        self.adminLable = QtWidgets.QLabel(newUser)
        self.adminLable.setGeometry(QtCore.QRect(330, 60, 111, 21))
        self.adminLable.setStyleSheet("color: rgb(151, 0, 111);\n"
"background-color: rgb(255, 255, 255);")
        self.adminLable.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.adminLable.setAlignment(QtCore.Qt.AlignCenter)
        self.adminLable.setObjectName("adminLable")
        self.label = QtWidgets.QLabel(newUser)
        self.label.setGeometry(QtCore.QRect(20, 20, 461, 251))
        self.label.setMinimumSize(QtCore.QSize(461, 251))
        self.label.setMaximumSize(QtCore.QSize(461, 251))
        self.label.setStyleSheet("color: rgb(151, 0, 111);")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setText("")
        self.label.setObjectName("label")
        self.nameLable = QtWidgets.QLabel(newUser)
        self.nameLable.setGeometry(QtCore.QRect(390, 120, 41, 20))
        self.nameLable.setStyleSheet("color: rgb(151, 0, 111);\n"
"background-color: rgb(255, 255, 255);")
        self.nameLable.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.nameLable.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLable.setObjectName("nameLable")
        self.adminpassword = QtWidgets.QLineEdit(newUser)
        self.adminpassword.setGeometry(QtCore.QRect(70, 60, 251, 21))
        self.adminpassword.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(151, 0, 111);\n"
"border-color: rgb(151, 0, 111);\n"
"padding : 2px;")
        self.adminpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.adminpassword.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.adminpassword.setObjectName("adminpassword")
        self.label_2 = QtWidgets.QLabel(newUser)
        self.label_2.setGeometry(QtCore.QRect(390, 10, 81, 21))
        self.label_2.setStyleSheet("color: rgb(151, 0, 111);\n"
"background-color: rgb(255, 255, 255);")
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.passwordLable = QtWidgets.QLabel(newUser)
        self.passwordLable.setGeometry(QtCore.QRect(360, 150, 81, 20))
        self.passwordLable.setStyleSheet("color: rgb(151, 0, 111);\n"
"background-color: rgb(255, 255, 255);")
        self.passwordLable.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.passwordLable.setAlignment(QtCore.Qt.AlignCenter)
        self.passwordLable.setObjectName("passwordLable")
        self.passwordText = QtWidgets.QLineEdit(newUser)
        self.passwordText.setGeometry(QtCore.QRect(70, 150, 291, 22))
        self.passwordText.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(151, 0, 111);\n"
"border-color: rgb(151, 0, 111);\n"
"padding : 2px;")
        self.passwordText.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordText.setObjectName("passwordText")
        self.newAccount = QtWidgets.QPushButton(newUser)
        self.newAccount.setGeometry(QtCore.QRect(160, 210, 141, 24))
        self.newAccount.setStyleSheet("background-color: rgb(151, 0, 111);\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Bernard MT Condensed\";\n"
"")
        self.newAccount.setObjectName("newAccount")
        self.label.raise_()
        self.NameText.raise_()
        self.adminLable.raise_()
        self.nameLable.raise_()
        self.adminpassword.raise_()
        self.label_2.raise_()
        self.passwordLable.raise_()
        self.passwordText.raise_()
        self.newAccount.raise_()

        self.retranslateUi(newUser)
        QtCore.QMetaObject.connectSlotsByName(newUser)

    def retranslateUi(self, newUser):
        _translate = QtCore.QCoreApplication.translate
        newUser.setWindowTitle(_translate("newUser", "creatAccount"))
        self.NameText.setPlaceholderText(_translate("newUser", "الاسم"))
        self.adminLable.setText(_translate("newUser", "ادخل كلمة مرور المدير :"))
        self.nameLable.setText(_translate("newUser", "الاسم :"))
        self.adminpassword.setPlaceholderText(_translate("newUser", "كلمة مرور المدير"))
        self.label_2.setText(_translate("newUser", "انشاء حساب"))
        self.passwordLable.setText(_translate("newUser", "كلمة المرور :"))
        self.passwordText.setPlaceholderText(_translate("newUser", "كلمة المرور"))
        self.newAccount.setText(_translate("newUser", "انشاء حساب"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    newUser = QtWidgets.QDialog()
    ui = Ui_newUser()
    ui.setupUi(newUser)
    newUser.show()
    sys.exit(app.exec_())
